server:
  port: 8083

spring:
  main:
    web-application-type: reactive
  application:
    name: microservicio-capacidad
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:capability_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: classpath:db/migration
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:adminpassword}
      roles: ADMIN

app:
  security:
    enabled: ${SECURITY_ENABLED:true}
  technology:
    base-url: ${TECHNOLOGY_BASE_URL:http://localhost:8084}
  http-client:
    credentials:
      username: ${HTTP_CLIENT_USERNAME:admin}
      password: ${HTTP_CLIENT_PASSWORD:adminpassword}

  
logging:
  level:
    root: INFO
    com.onclass: DEBUG
